/*
 * SerialPort.h
 *
 *  Created on: Nov 6, 2017
 *      Author: nvidia
 */

#ifndef HARDWARE_COMMUNICATION_INCLUDE_HARDWARE_COMMUNICATION_SERIALPORT_H_
#define HARDWARE_COMMUNICATION_INCLUDE_HARDWARE_COMMUNICATION_SERIALPORT_H_


#endif /* HARDWARE_COMMUNICATION_INCLUDE_HARDWARE_COMMUNICATION_SERIALPORT_H_ */
