(cl:defpackage nubot_common-srv
  (:use )
  (:export
   "BALLHANDLE"
   "<BALLHANDLE-REQUEST>"
   "BALLHANDLE-REQUEST"
   "<BALLHANDLE-RESPONSE>"
   "BALLHANDLE-RESPONSE"
   "GETMODELSTATE"
   "<GETMODELSTATE-REQUEST>"
   "GETMODELSTATE-REQUEST"
   "<GETMODELSTATE-RESPONSE>"
   "GETMODELSTATE-RESPONSE"
   "SHOOT"
   "<SHOOT-REQUEST>"
   "SHOOT-REQUEST"
   "<SHOOT-RESPONSE>"
   "SHOOT-RESPONSE"
  ))

